[package]
name = "project_api_axum"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
axum = "0.8.4"
log = "0.4.27"
pretty_env_logger = "0.5.0"